export const SET_FAST_LENGTH = 'SET_FAST_LENGTH';
export const SET_FAST_START_TIME = 'SET_FAST_START_TIME';
export const SET_FAST = 'SET_FAST';
export const SET_CURRENT_TIME = 'SET_CURRENT_TIME';
export const SET_FAST_TIME_LEFT = 'SET_FAST_TIME_LEFT';
